
  name: cass
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: A database GUI # 79 char long summary
  description: |
    This application provides GUI for cassandra database.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
