directories:
  output: release
  buildResources: resources
productName: Cass
name: Cass
appId: org.develar.cassandraDB
copyright: 'Copyright © 2019 ${author}'
files:
  - filter:
      - app/dist/
      - app/app.html
      - app/main.prod.js
      - app/main.prod.js.map
      - package.json
dmg:
  title: '${productName} ${version}'
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
  internetEnabled: true
mac:
  category: public.app-category.developer-tools
  type: development
  target: zip
  icon: resources/icon.icns
win:
  target:
    - nsis
    - msi
  icon: resources/icon.ico
linux:
  target:
    - zip
    - deb
  category: Development
  icon: ./resources/icon.icns
  executableName: cass
  synopsis: database operations
  description: This application can interact with cassandra database installed in your local system as well as live servers
  desktop:
    Name: Cass
    Icon: ./resources/icons/32x32.png
    Comment: Owner Free File System
    Categories: Network
  extraFiles:
    - from: 'resources/${os}/drivers'
      to: resources
      filter:
        - '**/*'
publish:
  provider: github
  owner: aamitsengar
  repo: cassandra-UI
  private: false
electronVersion: 3.0.10
